const app=document.querySelector('#app'), nav=document.querySelector('#seasonNav');
const esc=s=>String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function table(headers,rows){return `<table class="wikitable"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>`<td class="${i>1?'num':''}">${x}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function infobox(p){return `<table class="infobox"><tr><th colspan="2">${p.flag} ${p.name}</th></tr><tr><td>Born</td><td>${p.dob}<br>${p.birth}</td></tr><tr><td>Height</td><td>${p.height}</td></tr><tr><td>Position</td><td>${p.position}</td></tr><tr><td>Current team</td><td>${p.current}</td></tr><tr><td>Number</td><td>${p.number}</td></tr><tr><td>National team</td><td>${p.international}</td></tr></table>`}
function honours(p){return `<div class="honours">${Object.entries(p.honours).map(([k,v])=>`<section><h3>${k}</h3><ul>${v.map(x=>`<li>${x}</li>`).join('')}</ul></section>`).join('')}</div>`}
function player(id){let p=DATA[id]; nav.innerHTML=Object.keys(p.seasons).map(s=>`<a href="#${id}/${s}">${s}</a>`).join(''); app.innerHTML=`${infobox(p)}<h1>${p.name}</h1><p class="lede">${p.intro}</p><div class="toc"><b>Contents</b><ol><li><a href="#career">Club career</a></li><li><a href="#stats">Career statistics</a></li><li><a href="#honours">Honours</a></li><li><a href="#seasons">Season archive</a></li></ol></div><div class="clear"></div><div class="career-grid"><section><h2 id="career">Club career</h2>${table(['Years','Team','Apps','Goals'],p.career)}</section><section><h2>International career</h2>${table(['Years','Team','Apps','Goals'],[p.intl])}</section></div><h2 id="stats">Career statistics</h2>${table(['Season','Club','Role','League','Pos.','Avg','Apps','Goals','Assists','CLS'],p.stats)}<h2 id="seasons">Season-by-season archive</h2><p>Select a season to browse its recorded competitions and results.</p><div class="season-tabs">${Object.keys(p.seasons).map(s=>`<button onclick="location.hash='${id}/${s}'">${s}${p.seasons[s].inProgress?' •':''}</button>`).join('')}</div><h2 id="honours">Honours</h2>${honours(p)}`}
const FLAGS={
'PEC Zwolle':'🇳🇱','PSV':'🇳🇱','Ajax':'🇳🇱','Feyenoord':'🇳🇱','AZ':'🇳🇱','FC Utrecht':'🇳🇱','FC Twente':'🇳🇱','Telstar':'🇳🇱','N.E.C. Nijmegen':'🇳🇱','Go Ahead Eagles':'🇳🇱','FC Volendam':'🇳🇱','NAC Breda':'🇳🇱','Heracles Almelo':'🇳🇱','Sparta Rotterdam':'🇳🇱','FC Groningen':'🇳🇱','sc Heerenveen':'🇳🇱','Fortuna Sittard':'🇳🇱','Excelsior':'🇳🇱',
'Brighton & Hove':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Brighton & Hove Albion':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Bristol City':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Manchester City':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Manchester United':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Man Utd':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Liverpool':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Arsenal':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Chelsea':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Tottenham Hotspurs':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Tottenham':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Newcastle United':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','West Ham':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Fulham':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Everton':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Aston Villa':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Crystal Palace':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Nottingham Forest':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','AFC Bournemouth':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Wolves':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Sunderland':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Southampton':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Brentford':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Ipswich':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Norwich':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Sheffield United':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Leicester City':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Reading':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Blackburn Rovers':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Blackpool':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Bolton':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Coventry City':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Walsall':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Swansea City':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Leyton Orient':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Wigan Athletic':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Charlton Athletic':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Middlesbrough':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Crewe Alexandra':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Hull':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Burnley':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Watford':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Wycombe':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Lincoln City':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Oxford United':'🏴󠁧󠁢󠁥󠁮󠁧󠁿',
'FC Bayern München':'🇩🇪','Bayern':'🇩🇪','Borussia Dortmund':'🇩🇪','Dortmund':'🇩🇪','RB Leipzig':'🇩🇪','Leverkusen':'🇩🇪','Bayer Leverkusen':'🇩🇪','Hoffenheim':'🇩🇪','TSG Hoffenheim':'🇩🇪','Frankfurt':'🇩🇪','Eintracht Frankfurt':'🇩🇪','FC Augsburg':'🇩🇪','Augsburg':'🇩🇪','1. FC Köln':'🇩🇪','Köln':'🇩🇪','VfL Wolfsburg':'🇩🇪','VfB Stuttgart':'🇩🇪','Stuttgart':'🇩🇪','Mönchengladbach':'🇩🇪','Borussia Mönchengladbach':'🇩🇪','SC Freiburg':'🇩🇪','Freiburg':'🇩🇪','1. FSV Mainz 05':'🇩🇪','Mainz 05':'🇩🇪','SV Werder Bremen':'🇩🇪','Werder Bremen':'🇩🇪','Union Berlin':'🇩🇪','Hertha BSC':'🇩🇪','Hertha Berlin':'🇩🇪','Hamburger SV':'🇩🇪','Holstein Kiel':'🇩🇪','FC St. Pauli':'🇩🇪','Schalke 04':'🇩🇪',
'Real Madrid':'🇪🇸','FC Barcelona':'🇪🇸','Atlético de Madrid':'🇪🇸','Real Sociedad':'🇪🇸','Athletic Club':'🇪🇸','Getafe CF':'🇪🇸','Sevilla FC':'🇪🇸','Villarreal':'🇪🇸','SD Huesca':'🇪🇸','Cultural Leonesa':'🇪🇸','RC Deportivo':'🇪🇸','RCD Espanyol':'🇪🇸',
'Juventus':'🇮🇹','AC Milan':'🇮🇹','Milano FC':'🇮🇹','Lombardia FC':'🇮🇹','SSC Napoli':'🇮🇹','AS Roma':'🇮🇹','Roma':'🇮🇹','Inter Milan':'🇮🇹','Inter':'🇮🇹','Monza':'🇮🇹','Palermo':'🇮🇹','Bergamo Calcio':'🇮🇹','Torino':'🇮🇹','Venezia':'🇮🇹',
'Paris SG':'🇫🇷','PSG':'🇫🇷','OM':'🇫🇷','LOSC Lille':'🇫🇷','OGC Nice':'🇫🇷','Strasbourg':'🇫🇷','Stade Rennais FC':'🇫🇷','Havre AC':'🇫🇷',
'Celtic':'🏴','Rangers':'🏴','Motherwell':'🏴','Sporting CP':'🇵🇹','SL Benfica':'🇵🇹','FC Porto':'🇵🇹','SC Braga':'🇵🇹','F.C. Famalicão':'🇵🇹','Brøndby IF':'🇩🇰','FC Nordsjælland':'🇩🇰','F.C. København':'🇩🇰','Sparta Praha':'🇨🇿','Slavia Praha':'🇨🇿','Viktoria Plzeň':'🇨🇿','Dynamo Kyiv':'🇺🇦','Shakhtar Donetsk':'🇺🇦','Fenerbahçe':'🇹🇷','Galatasaray':'🇹🇷','Beşiktaş':'🇹🇷','Trabzonspor':'🇹🇷','Olympiacos FC':'🇬🇷','PAOK FC':'🇬🇷','Panathinaikos':'🇬🇷','Ajax':'🇳🇱','Feyenoord':'🇳🇱','Standard de Liège':'🇧🇪','RSC Anderlecht':'🇧🇪','KRC Genk':'🇧🇪','KV Mechelen':'🇧🇪','FC Basel 1893':'🇨🇭','BSC Young Boys':'🇨🇭','Rosenborg BK':'🇳🇴','FK Bodø/Glimt':'🇳🇴','Malmö FF':'🇸🇪','Malmo FF':'🇸🇪','Legia Warszawa':'🇵🇱','Raków':'🇵🇱','Lech Poznań':'🇵🇱','FCSB':'🇷🇴','FC Rapid 1923':'🇷🇴','CFR 1907 Cluj':'🇷🇴','Qarabağ FK':'🇦🇿','Ferencvárosi TC':'🇭🇺','APOEL FC':'🇨🇾','Dinamo Zagreb':'🇭🇷','Aberdeen':'🏴','Estrela Amadora':'🇵🇹','R. Union St.-G':'🇧🇪',
'England':'🏴󠁧󠁢󠁥󠁮󠁧󠁿','Netherlands':'🇳🇱','Scotland':'🏴󠁧󠁢󠁳󠁣󠁴󠁿','Wales':'🏴','Northern Ireland':'🇬🇧','Ireland':'🇮🇪','France':'🇫🇷','Germany':'🇩🇪','Spain':'🇪🇸','Italy':'🇮🇹','Belgium':'🇧🇪','Portugal':'🇵🇹','Sweden':'🇸🇪','Ukraine':'🇺🇦','Croatia':'🇭🇷','Hungary':'🇭🇺','Austria':'🇦🇹','Poland':'🇵🇱','Finland':'🇫🇮','Norway':'🇳🇴','Romania':'🇷🇴','Türkiye':'🇹🇷','Turkiye':'🇹🇷','Bosnia-Herzegov':'🇧🇦','Czechia':'🇨🇿','Switzerland':'🇨🇭','Iceland':'🇮🇸','Japan':'🇯🇵','Mexico':'🇲🇽','Brazil':'🇧🇷','Belgium':'🇧🇪','Ghana':'🇬🇭','Panama':'🇵🇦','Colombia':'🇨🇴','Canada':'🇨🇦','Curaçao':'🇨🇼','Morocco':'🇲🇦','Senegal':'🇸🇳','Saudi Arabia':'🇸🇦','IR Iran':'🇮🇷','Korea Republic':'🇰🇷','Algeria':'🇩🇿','Congo DR':'🇨🇩','Uruguay':'🇺🇾','Cote d\'Ivorie':'🇨🇮','United States':'🇺🇸','Egypt':'🇪🇬','New Zealand':'🇳🇿','Jordan':'🇯🇴','Iraq':'🇮🇶','Ecuador':'🇪🇨','Serbia':'🇷🇸','Slovenia':'🇸🇮','Slovakia':'🇸🇰','Greece':'🇬🇷','Albania':'🇦🇱','Georgia':'🇬🇪','Denmark':'🇩🇰','Australia':'🇦🇺','Tunisia':'🇹🇳','Cameroon':'🇨🇲','Nigeria':'🇳🇬','South Africa':'🇿🇦','Costa Rica':'🇨🇷','Jamaica':'🇯🇲','Paraguay':'🇵🇾','Chile':'🇨🇱','Peru':'🇵🇪','Venezuela':'🇻🇪','Bolivia':'🇧🇴','China PR':'🇨🇳','Qatar':'🇶🇦','United Arab Emirates':'🇦🇪','Uzbekistan':'🇺🇿','Honduras':'🇭🇳','El Salvador':'🇸🇻'
};
function teamFlag(t){if(FLAGS[t])return FLAGS[t];const x=t.toLowerCase();if(/bayern|dortmund|leverkusen|stuttgart|wolfsburg|mönchengladbach|monchengladbach|freiburg|mainz|bremen|frankfurt|augsburg|hoffenheim|hertha|hamburg|holstein|köln|koln|leipzig|union berlin|schalke/.test(x))return '🇩🇪';return '🏳️'}
function sectionId(name){return 'section-'+name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function parseFixture(raw){let label='',x=raw.trim();if(x.includes(' — ')){let a=x.split(' — ');label=a.shift();x=a.join(' — ')}let m=x.match(/^(.+?)\s+(?:\((\d+)\)\s*)?(\d+)\s*-\s*(\d+)(?:\s*\((\d+)\))?\s+(.+)$/);if(!m)return {raw,label};return {label,home:m[1].trim(),hp:m[2]?+m[2]:null,hg:+m[3],ag:+m[4],ap:m[5]?+m[5]:null,away:m[6].trim()}}
function focalFor(id,s,comp){if(/World Cup|Euros|Qualif|Friendl/i.test(comp))return id==='rens'?'Netherlands':'England';let row=DATA[id].stats.find(r=>r[0]===s);if(!row)return '';let club=String(row[1]).replace(/^\S+\s/,'');if(club==='Brighton')return 'Brighton & Hove';if(club==='Bayern')return 'FC Bayern München';if(club==='Dortmund')return 'Borussia Dortmund';return club}
function sameTeam(a,b){const n=x=>x.toLowerCase().replace(/fc |afc |& hove albion|borussia |münchen/g,'').replace(/\s+/g,' ').trim();return n(a)===n(b)||n(a).includes(n(b))||n(b).includes(n(a))}
function outcome(f,focal){if(!f.home||(!sameTeam(f.home,focal)&&!sameTeam(f.away,focal)))return 'neutral';let homeWin=f.hg>f.ag,awayWin=f.ag>f.hg;if(f.hg===f.ag&&f.hp!=null&&f.ap!=null){homeWin=f.hp>f.ap;awayWin=f.ap>f.hp}if(!homeWin&&!awayWin)return 'draw';let focalHome=sameTeam(f.home,focal);return (focalHome&&homeWin)||(!focalHome&&awayWin)?'win':'loss'}
function tournamentRounds(comp,items){if(comp==='Euros'&&items.length>=18)return {0:'Group stage',3:'Round of 16',11:'Quarter-finals',15:'Semi-finals',17:'Final'};if(comp==='World Cup'&&items.length>=35)return {0:'Group stage',3:'Round of 32',19:'Round of 16',27:'Quarter-finals',31:'Semi-finals',33:'Third-place / Final stage',34:'Final'};return {}}
function fixtureTable(items,focal,comp){let breaks=tournamentRounds(comp,items);let rows=items.map((raw,i)=>{let heading=breaks[i]?`<tr class="round-separator"><th colspan="6">${breaks[i]}</th></tr>`:'';let f=parseFixture(raw);if(!f.home)return heading+`<tr><td colspan="5">${esc(raw)}</td><td class="marker neutral"></td></tr>`;let score=`${f.hp!=null?`(${f.hp}) `:''}${f.hg} - ${f.ag}${f.ap!=null?` (${f.ap})`:''}`;let title=f.label?` title="${esc(f.label)}"`:'';return heading+`<tr${title}><td class="flag">${teamFlag(f.home)}</td><td class="team home">${esc(f.home)}</td><td class="scorecell">${score}</td><td class="team away">${esc(f.away)}</td><td class="flag">${teamFlag(f.away)}</td><td class="marker ${outcome(f,focal)}"></td></tr>`}).join('');return `<table class="fixture-table"><tbody>${rows}</tbody></table>`}
function season(id,s){let p=DATA[id],d=p.seasons[s],full=(FULL_FIXTURES[id]&&FULL_FIXTURES[id][s])||{};nav.innerHTML=`<a href="#${id}">← ${p.name}</a>`+Object.keys(p.seasons).map(x=>`<a href="#${id}/${x}">${x}</a>`).join('');let entries=Object.entries(full).filter(([k,v])=>v.length);let jump=entries.length?`<nav class="season-jump"><b>On this season</b><div>${entries.map(([k])=>`<a href="#${sectionId(k)}" onclick="event.preventDefault();document.getElementById('${sectionId(k)}').scrollIntoView({behavior:'smooth',block:'start'})">${k}</a>`).join('')}</div></nav>`:'';let blocks=entries.map(([k,v])=>`<section class="competition" id="${sectionId(k)}"><h2>${k}</h2>${fixtureTable(v,focalFor(id,s,k),k)}</section>`).join('');app.innerHTML=`<p><a href="#${id}">← ${p.name}</a></p><h1>${p.flag} ${p.name}: ${s}</h1>${d.inProgress?'<p><span class="status">In progress</span></p>':''}<p class="lede">${d.summary}</p><div class="note league-record"><b>League record:</b> ${d.table}</div>${jump}<p class="muted">Full fixture and result archive from the supplied season data. Green = win, amber = draw, red = loss. Grey marks tournament results not involving the player’s team. Blank/unplayed fixtures are not shown.</p>${blocks||'<p>No scored fixtures have been recorded yet.</p>'}`}
function home(){nav.innerHTML='';app.innerHTML=`<h1>FC26 Career Wiki</h1><p class="lede">An encyclopedia-style archive of FC26 player careers, club seasons, international tournaments and honours.</p><div class="note">The archive currently covers two players. In-progress seasons are labelled and incomplete data is never treated as final.</div><h2>Players</h2><div class="cards">${Object.entries(DATA).map(([id,p])=>`<div class="card"><h3><a href="#${id}">${p.flag} ${p.name}</a></h3><p>${p.position}</p><p class="muted">${p.current}</p><a href="#${id}">View career article →</a></div>`).join('')}</div><h2>About this archive</h2><p>Use the player articles for career summaries and honours, then open individual seasons for competition-by-competition records. Country flags identify clubs and national teams throughout the archive.</p>`}
function route(){let h=decodeURIComponent(location.hash.slice(1)||'home'), [id,s]=h.split('/'); if(id==='home')home(); else if(DATA[id]&&s&&DATA[id].seasons[s])season(id,s); else if(DATA[id])player(id); else home(); window.scrollTo(0,0)}
addEventListener('hashchange',route);route();
document.querySelector('#search').addEventListener('keydown',e=>{if(e.key==='Enter'){let q=e.target.value.toLowerCase();let id=Object.keys(DATA).find(k=>DATA[k].name.toLowerCase().includes(q)||JSON.stringify(DATA[k]).toLowerCase().includes(q));if(id)location.hash=id;}});
